import type { RouteCrowdPathProviderLike, RouteCrowdViewport } from "./routeCrowd.js";
export interface BugCrowdPoint { readonly x:number; readonly y:number; }
export interface BugCrowdRange { readonly minMs:number; readonly maxMs:number; }
export type BugCrowdMode="wander"; export type BugCrowdState="moving"|"waiting";
export interface BugCrowdConfig { readonly id:string; readonly startTiles:readonly BugCrowdPoint[]; readonly endTiles:readonly BugCrowdPoint[]; readonly npcCount:number; readonly movementSpeed:number; readonly speedVariation:number; readonly mode:BugCrowdMode; readonly randomPositions:boolean; readonly wanderDistance:number; readonly wanderInterval:BugCrowdRange; readonly sprite:string; readonly maxActiveInViewport:number; }
export interface BugCrowdInstanceSnapshot { readonly id:string; readonly position:BugCrowdPoint; readonly state:BugCrowdState; readonly sprite:string; readonly materialized:boolean; }
export interface BugCrowdSnapshot { readonly instances:readonly BugCrowdInstanceSnapshot[]; }
export type BugCrowdViewport=RouteCrowdViewport;
export interface BugCrowdRuntimeOptions { readonly pathProvider:RouteCrowdPathProviderLike; readonly random?:()=>number; }
export const BUG_CROWD_TILE_SIZE=16;
const tile=(x:number,y:number)=>Object.freeze({x,y});
export const BUG_CROWD_CONFIG:BugCrowdConfig=Object.freeze({id:"bug-area",startTiles:Object.freeze([[5,128],[9,129],[13,130],[17,131],[21,132],[7,133],[11,128],[15,129],[19,130]].map(([x,y])=>tile(x!,y!))),endTiles:Object.freeze([[23,133],[19,132],[15,131],[11,130],[7,129],[21,128],[17,133],[13,132],[9,131]].map(([x,y])=>tile(x!,y!))),npcCount:10,movementSpeed:15,speedVariation:.3,mode:"wander" as const,randomPositions:true,wanderDistance:24,wanderInterval:Object.freeze({minMs:2_000,maxMs:4_000}),sprite:"npc-bug",maxActiveInViewport:40});
export const BUG_CROWD_CONFIGS=Object.freeze([BUG_CROWD_CONFIG]);
type Item={id:string;position:BugCrowdPoint;state:BugCrowdState;sprite:string;materialized:boolean;path:readonly BugCrowdPoint[];index:number;nextAt:number;speed:number};
const world=(p:BugCrowdPoint)=>({x:p.x*16+8,y:p.y*16+8}); const provider=(p:RouteCrowdPathProviderLike,start:BugCrowdPoint,end:BugCrowdPoint)=>typeof p==="function"?p({start,end}):p.findPath({start,end});
const empty=():BugCrowdSnapshot=>Object.freeze({instances:Object.freeze([])});
export class BugCrowdRuntime { private items:Item[]=[];private last=0;private dead=false;private readonly random:()=>number; constructor(private readonly o:BugCrowdRuntimeOptions){this.random=o.random??Math.random;} get snapshot():BugCrowdSnapshot{return Object.freeze({instances:Object.freeze(this.items.map(({path,index,nextAt,speed,...x})=>Object.freeze({...x,position:Object.freeze({...x.position})}))) });} start(now:number,view?:BugCrowdViewport){if(this.dead)return this.snapshot;this.last=now;this.items=[];for(let i=0;i<10;i++){const start=world(BUG_CROWD_CONFIG.startTiles[Math.floor(this.random()*9)]!);const item:Item={id:`bug-area:${i}`,position:start,state:"moving",sprite:"npc-bug",materialized:false,path:[],index:1,nextAt:now+this.delay(),speed:15*(.7+this.random()*.6)};this.choose(item);this.items.push(item);}this.view(view);return this.snapshot;} tick(now:number,view?:BugCrowdViewport){const elapsed=Math.max(0,now-this.last);this.last=now;for(const item of this.items){if(now>=item.nextAt){this.choose(item);item.nextAt=now+this.delay();}let left=elapsed;while(left>0){if(item.path[item.index]===undefined){if(now<item.nextAt){item.state="waiting";break;}this.choose(item);item.nextAt=now+this.delay();continue;}item.state="moving";const target=item.path[item.index]!,dx=target.x-item.position.x,dy=target.y-item.position.y,d=Math.hypot(dx,dy),a=item.speed*left/1000;if(a<d){item.position={x:item.position.x+dx*a/d,y:item.position.y+dy*a/d};left=0;}else{item.position=target;item.index++;left-=d/item.speed*1000;}}}this.view(view);return this.snapshot;} cancel(){this.items=[];return this.snapshot;} shutdown(){this.dead=true;return this.cancel();} private choose(item:Item){const end=world(BUG_CROWD_CONFIG.endTiles[Math.floor(this.random()*9)]!);item.path=provider(this.o.pathProvider,item.position,end)??[];item.index=1;}private delay(){return 2_000+this.random()*2_000;}private view(v?:BugCrowdViewport){if(!v)return;for(const i of this.items)i.materialized=i.position.x>=v.left&&i.position.x<=v.left+v.width&&i.position.y>=v.top&&i.position.y<=v.top+v.height;}}
