import {
  DANCING_DIRECTIONS,
  DancingCrowdRuntime,
  type DancingCrowdConfig,
} from "../src/npc/index.js";
import type { DancingCrowdPresentation } from "../config/骨架/05-旁支/SYS-NPC/逻辑/types.js";
type Sprite={x:number;y:number;setScale(x:number):unknown;setDepth(n:number):unknown;anims?:{play(k:string,b?:boolean):unknown};destroy():void};
export interface PhaserDancingCrowdSceneLike { readonly add:{sprite(x:number,y:number,k:string):Sprite}; readonly textures:{exists(k:string):boolean}; readonly anims:{exists?(k:string):boolean;create(x:unknown):unknown;generateFrameNumbers(k:string,r:{start:number;end:number}):unknown[]}; }
export function preloadDancingCrowdRuntimeAssets(loader:{spritesheet(k:string,u:string,c:{frameWidth:number;frameHeight:number}):unknown},p:DancingCrowdPresentation){for(const direction of DANCING_DIRECTIONS)loader.spritesheet(`${p.textureKeyPrefix}${direction}`,`${p.textureUrlPrefix}${direction}${p.textureUrlSuffix}`,{frameWidth:p.textureFrameWidth,frameHeight:p.textureFrameHeight});}
export class PhaserDancingCrowdRuntime { private readonly core:DancingCrowdRuntime;private sprites=new Map<string,Sprite>();constructor(private readonly scene:PhaserDancingCrowdSceneLike,private readonly viewport:()=>{left:number;top:number;width:number;height:number}|undefined,private readonly config:DancingCrowdConfig,private readonly presentation:DancingCrowdPresentation){this.core=new DancingCrowdRuntime(config);} start(){if(!DANCING_DIRECTIONS.every(d=>this.scene.textures.exists(`${this.presentation.textureKeyPrefix}${d}`)))return false;for(const d of DANCING_DIRECTIONS){const k=`${this.presentation.textureKeyPrefix}${d}-anim`;if(!this.scene.anims.exists?.(k))this.scene.anims.create({key:k,frames:this.scene.anims.generateFrameNumbers(`${this.presentation.textureKeyPrefix}${d}`,{start:this.presentation.animationFrameStart,end:this.presentation.animationFrameEnd}),frameRate:this.config.frameRate,repeat:-1});}this.core.start(this.viewport());this.sync();return true;}update(){this.core.tick(this.viewport());this.sync();}shutdown(){this.core.shutdown();for(const s of this.sprites.values())s.destroy();this.sprites.clear();}private sync(){const ids=new Set<string>();for(const i of this.core.snapshot.instances){if(!i.materialized)continue;ids.add(i.id);const key=`${this.presentation.textureKeyPrefix}${i.direction}`,s=this.sprites.get(i.id)??this.scene.add.sprite(i.x,i.y,key);s.x=i.x;s.y=i.y;s.setScale(this.config.scale);s.setDepth(this.config.depth);s.anims?.play(`${key}-anim`,true);this.sprites.set(i.id,s);}for(const[id,s]of this.sprites)if(!ids.has(id)){s.destroy();this.sprites.delete(id);}}}
